SOURCES = ./Metro/metro.ml ./Heap/heap.mli ./Heap/heap.ml ./RedBlackTree/redBlack.mli ./RedBlackTree/redBlack.ml dijkstra.ml main.ml
RESULT = my-dijkstra
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)